### ISSUE TITLE
Suggestion on appearance, data missing(?) in version 0.0.3

### ISSUE THREAD

**Issue by ChaozR** [popojan/goban#39] opened 2022-01-24 07:54 UTC
First of all, thank you for building this lovely Goban program.

I love the idea displaying dead stones on bowl's cap(not so sure how they are called in English). However, it is more common to place stone bowls and caps in the other way around(please see attachment). It would be grateful if you can implement like attachment someday :) 

And somehow I cannot run Red Carpet and Minimalistic Flat skin on version 22-01-05 (only shows black screen, but program still runs), while version 21-05-31 has no problem. 

![K-044](https://user-images.githubusercontent.com/46801011/150740831-64db6ada-545b-4220-bad4-2db8ea757c17.png)

**Comment by popojan** [comment] 2022-01-31 21:42
Hi ChaozR, thank you for the suggestion and bug report!

I will look into the black screen bug. It may require your assistance if I were not able to reproduce it. Is there a log 
file created in the Goban root folder?

As for the bowl placement I will be glad to implement it. Just out of curiosity, where does the TV picture come from? Is it a rendered image or a photo?

**Comment by popojan** [comment] 2022-02-01 02:03
I can reproduce the problem on my freshly updated linux system.

**Comment by ChaozR** [comment] 2022-02-03 00:39
> Just out of curiosity, where does the TV picture come from? Is it a rendered image or a photo?

The picture is captured on Youtube. It was live broadcast on the game between Lee sedol 9p and Kejie 9p. The goban and stones are real one

**Comment by popojan** [comment] 2022-02-03 14:21
Thank you for your reply.

Both the black screen problem and the customary lid position should be addressed by the minor release [2022-02-03](https://hraj.si/goban/).

**Closed** 2022-09-08 22:33 UTC
Labels: bug, enhancement
